name: tap_hoa_pt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

fonts:
- family: Merriweather
  fonts:
    - asset: assets/fonts/Merriweather-Regular.ttf
    - asset: assets/fonts/Merriweather-Bold.ttf
      weight: 700
    - asset: assets/fonts/Merriweather-Italic.ttf
      style: italic